image: openjdk:11

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  script:
    ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/TEST*.xml
production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    #                        App name from prev step  Key from your heroku account
    - dpl --provider=heroku --app=simple-autos-data --api-key=cf4a3cfe-b0aa-458c-8473-6d82ff9f3334
  only: # Heroku will ONLY deploy from main or master branch!
    - master