apiVersion: apps/v1
kind: Deployment
metadata:
  name: autos
  labels:
    app: autos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autos
  template:
    metadata:
      labels:
        app: autos
    spec:
      containers:
        - name: autos
          image: lene626/autos
          ports:
            - containerPort: 8080