apiVersion: v1
kind: Service
metadata:
  name: mdacosta-simple-autos
spec:
  type: LoadBalancer
  selector:
    app: mdacosta-simple-autos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http